// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "behavior",
  id: "mikal_cannon_3d_physics",
  name: "Cannon 3D Physics",
  version: "1.2.0",
  category:
    // "attributes",
    "movements",
    // "other",
    // "general",
  author: "Mikal",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "Description",
  // icon: "icon.svg", // defaults to "icon.svg" if omitted
  // addonUrl: "https://www.construct.net/en/make-games/addons/####/XXXX", // displayed in auto-generated docs
  // githubUrl: "https://github.com/skymen/XXXX", // displays latest release version in auto-generated docs
  fileDependencies: [
    /*
    {
      filename: "filename.js", // no need to include "c3runtime/" prefix
      type:
        "copy-to-output"
        "inline-script"
        "external-dom-script"
        "external-runtime-script"
        "external-css"

      // for copy-to-output only
      // fileType: "image/png"
    }
    */
   {
    filename: "cannon-es.js",
    type: "inline-script",
   }
  ],
  info: {
    Set: {
      IsOnlyOneAllowed: false,
      CanBeBundled: false,
      IsDeprecated: false,
    },
  },
  properties: [
    /*
    {
      type:
        "integer"
        "float"
        "percent"
        "text"
        "longtext"
        "check"
        "font"
        "combo"
        "group"
        "link"
        "info"

      id: "property_id",
      options: {
        initialValue: 0,
        interpolatable: false,

        // minValue: 0, // omit to disable
        // maxValue: 100, // omit to disable

        // for type combo only
        // items: [
        //   {itemId1: "item name1" },
        //   {itemId2: "item name2" },
        // ],

        // dragSpeedMultiplier: 1, // omit to disable

        // for type link only
        // linkCallback: `function(instOrObj) {}`,
        // linkText: "Link Text",
        // callbackType:
        //   "for-each-instance"
        //   "once-for-type"

        // for type info only
        // infoCallback: `function(inst) {}`,
      },
      name: "Property Name",
      desc: "Property Description",
    }
    */
   {
    type: "check",
    id: "enable",
    name: "Enable",
    desc: "Enable physics",
    options: {
      initialValue: true,
    }
   },
   {
    type: "check",
    id: "immovable",
    name: "Immovable",
    desc: "Immovable body.",
    options: {
      initialValue: false,
    }
   },
   {
    type: "combo",
    id: "shape",
    name: "Shape",
    desc: "Immovable body.",
    options: {
      initialValue: "auto",
      items: [
        { "auto": "Auto" },
        { "box": "Box" },
      ]
    }
   },
  ],
  aceCategories: {
    // follows the format id: langName
    // in the ACEs refer to categories using the id, not the name
    general: "General",
    world: "World",
    body: "Body",
  },
  Acts: {
    SetWorldGravity: {
      // The category of the action as it appears in the add action dialog
      category: "world",

      // Or specify a handler function
      forward: "_SetWorldGravity",
      autoScriptInterface: true,
      highlight: true,
      deprecated: false,
      isAsync: false,
      // list of parameters
      params: [
        {
          id: "gravityX",
          name: "Gravity X",
          desc: "Gravity in X axis.",
          type: "number",
          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "0",
        },
        {
          id: "gravityY",
          name: "Gravity Y",
          desc: "Gravity in Y axis.",
          type: "number",
          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "0",
        },
        {
          id: "gravityZ",
          name: "Gravity Z",
          desc: "Gravity in Z axis.",
          type: "number",
          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "0",
        },
      ],

      // The name of the action as it appears in the add action dialog
      listName: "Set world gravity",
      displayText: "{my}: Set world gravity [i]{0},{1},{2}[/i]",
      // The description of the action as it appears in the add action dialog
      description: "Set world gravity in x,y,z axis.",
    },
    Raycast: {
      // The category of the action as it appears in the add action dialog
      category: "general",
      forward: "_Raycast",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isAsync: false,
      // list of parameters
      params: [
        {
          id: "tag",
          name: "Tag",
          desc: "Tag for request.",
          type: "string",
          value: "",
        },
        {
          id: "fromX",
          name: "From x",
          desc: "From x.",
          type: "number",
          value: "0",
        },
        {
          id: "fromY",
          name: "From y",
          desc: "From y.",
          type: "number",
          value: "0",
        },
        {
          id: "fromZ",
          name: "From z",
          desc: "From z.",
          type: "number",
          value: "0",
        },
        {
          id: "toX",
          name: "To x",
          desc: "To x.",
          type: "number",
          value: "0",
        },
        {
          id: "toY",
          name: "To y",
          desc: "To y.",
          type: "number",
          value: "0",
        },
        {
          id: "toZ",
          name: "To z",
          desc: "To z.",
          type: "number",
          value: "0",
        },
      ],
      listName: "Raycast from to",
      displayText: "{my}: Raycast , tag {0} from [i]{1},{2},{3}[/i] to [i]{4},{5},{6}[/i]",
      // The description of the action as it appears in the add action dialog
      description: "Raycast from x0,y0,z0 to x1,y1,z1.",
    },
    ApplyImpulse: {
      // The category of the action as it appears in the add action dialog
      category: "body",
      forward: "_ApplyImpulse",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isAsync: false,
      // list of parameters
      params: [
        {
          id: "impulseX",
          name: "Impulse x",
          desc: "Impuese vector x.",
          type: "number",
          value: "0",
        },
        {
          id: "impulseY",
          name: "Impulse y",
          desc: "Impuese vector y.",
          type: "number",
          value: "0",
        },
        {
          id: "impulseZ",
          name: "Impulse z",
          desc: "Impuese vector z.",
          type: "number",
          value: "0",
        }
      ],
      listName: "Apply impulse",
      displayText: "Apply {my} impulse {0}, {1} , {2}",
      // The description of the action as it appears in the add action dialog
      description: "Apply impulse to body.",
    },
    SetImmovable: {
      // The category of the action as it appears in the add action dialog
      category: "body",
      forward: "_SetImmovable",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isAsync: false,
      // list of parameters
      params: [
        {
          id: "immovable",
          name: "Immovable",
          desc: "Immovable body.",
          type: "boolean",
          value: "false",
        },

      ],
      listName: "Set immovable",
      displayText: "Set {my} immovable {0}",
      // The description of the action as it appears in the add action dialog
      description: "Set body immovable.",
    },
    EnablePhysics: {
      // The category of the action as it appears in the add action dialog
      category: "body",
      forward: "_EnablePhysics",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isAsync: false,
      // list of parameters
      params: [
        {
          id: "enable",
          name: "Enable",
          desc: "Enable body.",
          type: "boolean",
          value: "false",
        },

      ],
      listName: "Enable physics",
      displayText: "Enable {my} physics {0}",
      // The description of the action as it appears in the add action dialog
      description: "Enable body physics.",
    },    
    /*
    SampleAction: {
      // The category of the action as it appears in the add action dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this action
      // Cases where you might not want this are:
      // 1- If the action params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the action in the add action dialog
      highlight: true,

      // Set to true to hide the action in the interface. False by default if not specified.
      deprecated: false,

      // Marks the action as async. Defaults to false if not specified.
      isAsync: false,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the action as it appears in the add action dialog
      listName: "Sample Action",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      // You can also use the {my} tag to include the behavior icon and name.
      displayText: "{my}: Sample action [i]{0}[/i]",

      // The description of the action as it appears in the add action dialog
      description: "This is a sample action",
    },
    */
  },
  Cnds: {
    IsEnabled: {
      // The category of the action as it appears in the add condition dialog
      category: "body",
      forward: "_IsEnabled",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isTrigger: false,
      isFakeTrigger: false,
      isStatic: false,
      isLooping: false,
      isInvertible: true,
      isCompatibleWithTriggers: true,
      // list of parameters
      params: [
      ],

      listName: "Is enabled",
      displayText: "{my}: is enabled",
      description: "is physics enabled.",
    },
    IsImmovable: {
      // The category of the action as it appears in the add condition dialog
      category: "body",
      forward: "_IsImmovable",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      isTrigger: false,
      isFakeTrigger: false,
      isStatic: false,
      isLooping: false,
      isInvertible: true,
      isCompatibleWithTriggers: true,
      // list of parameters
      params: [
      ],

      listName: "Is immovable",
      displayText: "{my}: is immovable",
      description: "is immovable.",
    },
    /*
    SampleCondition: {
      // The category of the action as it appears in the add condition dialog
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this condition
      // Cases where you might not want this are:
      // 1- If the condition params are incompatible with the script interface
      // 2- If you don't want it to appear in the script interface
      // 3- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the condition in the add condition dialog
      highlight: true,

      // Set to true to hide the condition in the interface. False by default if not specified.
      deprecated: false,

      // special conditions properties. These can all be omitted, and they will default to the following values:
      isTrigger: false,
      isFakeTrigger: false,
      isStatic: false,
      isLooping: false,
      isInvertible: true,
      isCompatibleWithTriggers: true,

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
            - "boolean"

            // The following types can take a default value but CANNOT be automatically generated in the script interface
            - "combo"

            // The following types CANNOT take a default value AND CANNOT be automatically generated in the script interface
            - "cmp"
            - "object"
            - "objectname"
            - "layer"
            - "layout"
            - "keyb"
            - "instancevar"
            - "instancevarbool"
            - "eventvar"
            - "eventvarbool"
            - "animation"
            - "objinstancevar"

          // The default value of the parameter. Can be omitted if the type is not a string, number, any, boolean or combo.
          value: "the default value of the parameter",

          // Only for type "combo"
          items: [
            {"itemId1": "itemName1"},
            {"itemId2": "itemName2"},
            {"itemId3": "itemName3"},
          ],

          // Only for type "object"
          allowedPluginIds: ["Sprite", "TiledBg"],
        },
      ],

      // The name of the condition as it appears in the add condition dialog
      listName: "Sample Condition",

      // The text that appears in the event sheet. Note, every single param must be used in the display text.
      // You can also use [b] and [i] tags.
      // You can also use the {my} tag to include the behavior icon and name.
      displayText: "{my}: Sample condition [i]{0}[/i]",

      // The description of the condition as it appears in the add condition dialog
      description: "This is a sample condition",
    },
    */
  },
  Exps: {
    RaycastResultAsJSON: {
      // The category of the action as it appears in the expression picker
      category: "general",
      forward: "_RaycastResultAsJSON",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      returnType: "string",
      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false,
      params: [
      ],
      description: "Raycast result as JSON string.",
    },
    Enable: {
      // The category of the action as it appears in the expression picker
      category: "body",
      forward: "_Enable",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      returnType: "number",
      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false,
      params: [
      ],
      description: "Physics enabled.",
    },
    WorldGravityX: {
      // The category of the action as it appears in the expression picker
      category: "world",
      forward: "_WorldGravityX",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      returnType: "number",
      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false,
      params: [
      ],
      description: "World gravity x vector.",
    },
    WorldGravityY: {
      // The category of the action as it appears in the expression picker
      category: "world",
      forward: "_WorldGravityY",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      returnType: "number",
      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false,
      params: [
      ],
      description: "World gravity y vector.",
    },
    WorldGravityZ: {
      // The category of the action as it appears in the expression picker
      category: "world",
      forward: "_WorldGravityZ",
      autoScriptInterface: true,
      highlight: false,
      deprecated: false,
      returnType: "number",
      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false,
      params: [
      ],
      description: "World gravity z vector.",
    },          
    /*
    SampleExpression: {
      // The category of the action as it appears in the expression picker
      category: "general",

      // Forward to the instance function name
      forward: "_SampleAction",
      // Or specify a handler function
      handler: `function () {
        // Your code here
      }`,

      // Set to true to automatically generate a script interface for this expression
      // Cases where you might not want this are:
      // 1- If you don't want it to appear in the script interface
      // 2- If the script interface has a better way to achieve the same thing
      autoScriptInterface: true,

      // Set to true to highlight the expression in the expression picker
      highlight: true,

      // Set to true to hide the expression in the interface. False by default if not specified.
      deprecated: false,

      // The type of the expression.
      returnType:
        - "string"
        - "number"
        - "any" // must be either string or number

      // Set to true if the expression is variadic. False by default if not specified.
      isVariadicParameters: false

      // list of parameters
      params: [
        {
          // The id of the parameter. This is used to generate the script interface.
          // It must be unique for each parameter.
          id: "param1",
          // The name of the parameter.
          name: "Param 1",
          // The description of the parameter.
          desc: "The first parameter",

          // The type of the parameter.
          type:
            // The following types can take a default value AND be automatically generated in the script interface
            - "string"
            - "number"
            - "any"
        },
      ],

      // The description of the expression as it appears in the expression picker
      description: "This is a sample expression",
    },
    */
  },
};
